version: '3.8'

services:
  fastapi-app:
    build: 
      context: .
      dockerfile: ./DockerFile
    container_name: vitibrasil-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
